### ISSUE TITLE
How to set the font of mermaid?

### ISSUE THREAD

**Issue by fuzihaofzh** [y-takey/atom-mermaid#15]
Hi, thanks for your plugins and I want to know how to set font of atom-mermaid? The font of my preview seems too small.

**Comment by y-takey** [comment]
Hi, @maplewizard !

The function to change the font size is not yet implemented.
But you can set font via atom editor function.
In Atom, click the `[Open Your Stylesheet]`, then write any css to styles.less. and save it. 
e.g.

``` less
.atom-mermaid-preview {  /* <- this css class is root */
  font-size: 16px;
}
```
